# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=200)),
                ('user_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('source_device', models.CharField(max_length=200)),
                ('is_retweeted', models.BooleanField(default=False)),
                ('retweet_count', models.PositiveIntegerField(default=0)),
                ('country', models.CharField(max_length=200)),
                ('country_code', models.CharField(max_length=200)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('favorite_count', models.PositiveIntegerField(default=0)),
                ('tweet_text', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField()),
                ('timestamp_ms', models.CharField(max_length=200)),
                ('lang', models.CharField(max_length=200)),
                ('tweet_id', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'ordering': ['modified_date'],
                'db_table': 'tweets_data',
            },
        ),
    ]
