# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweetapp', '0002_auto_20180131_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
            ],
            options={
                'ordering': ['modified_date'],
                'db_table': 'tweets_hashtags',
            },
        ),
        migrations.AddField(
            model_name='tweets',
            name='hash_tags',
            field=models.ManyToManyField(null=True, to='tweetapp.HashTags'),
        ),
    ]
